package:
  name: plywood
  version: "1.10.0"

source:
  fn: plywood-1.10.0.tar.gz
  url: https://pypi.python.org/packages/source/p/plywood/plywood-1.10.0.tar.gz
  md5: f756f0d3530b131cfbbcabc2c9f2e55d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - plywood = plywood:main
    #
    # Would create an entry point called plywood that calls plywood.main()

    - ply = plywood.__main__:run

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - chomsky >=1.0.2

  run:
    - python
    - chomsky >=1.0.2

test:
  # Python imports
  imports:
    - plywood
    - plywood.plugins
    - test

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - ply --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/colinta/plywood
  license: BSD License
  summary: 'A template language grammar inspired by the Python code aesthetic'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
