package:
  name: colander
  version: "1.0"

source:
  fn: colander-1.0.tar.gz
  url: https://pypi.python.org/packages/source/c/colander/colander-1.0.tar.gz
  md5: 058576123da7216288c079c9f47693f8
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - colander = colander:main
    #
    # Would create an entry point called colander that calls colander.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - translationstring
    - iso8601
    - sphinx
    - nose
    - coverage

  run:
    - python
    - translationstring
    - iso8601
    - sphinx
    - nose
    - coverage

test:
  # Python imports
  imports:
    - colander
    - colander.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://docs.pylonsproject.org/projects/colander/en/latest/
  license: BSD-derived (http://www.repoze.org/LICENSE.txt)
  summary: 'A simple schema-based serialization and deserialization library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
