package:
  name: eve
  version: "0.5.3"

source:
  fn: Eve-0.5.3.tar.gz
  url: https://pypi.python.org/packages/source/E/Eve/Eve-0.5.3.tar.gz
  md5: 5d4c0cf9975b8cc12b7a7ad3d8f4a8e3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - eve = eve:main
    #
    # Would create an entry point called eve that calls eve.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cerberus >=0.8,<0.9
    - events >=0.2.1,<0.3
    - simplejson >=3.3.0,<4.0
    - werkzeug >=0.9.4,<0.11
    - markupsafe >=0.23,<1.0
    - jinja2 >=2.7.2,<3.0
    - itsdangerous >=0.22,<1.0
    - flask >=0.10.1,<0.11
    - pymongo >=2.7.1,<3.0
    - flask-pymongo >=0.3.0,<0.4

  run:
    - python
    - cerberus >=0.8,<0.9
    - events >=0.2.1,<0.3
    - simplejson >=3.3.0,<4.0
    - werkzeug >=0.9.4,<0.11
    - markupsafe >=0.23,<1.0
    - jinja2 >=2.7.2,<3.0
    - itsdangerous >=0.22,<1.0
    - flask >=0.10.1,<0.11
    - pymongo >=2.7.1,<3.0
    - flask-pymongo >=0.3.0,<0.4

test:
  # Python imports
  imports:
    - eve
    - eve.io
    - eve.io.mongo
    - eve.methods
    - eve.tests
    - eve.tests.io
    - eve.tests.methods

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - redis
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://python-eve.org
  license: BSD License
  summary: 'Python REST API for Humans.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
