package:
  name: haigha
  version: "0.8.0"

source:
  fn: haigha-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/h/haigha/haigha-0.8.0.tar.gz
  md5: 0f7f80733209a6e3e7494b8e0ef35650
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - haigha = haigha:main
    #
    # Would create an entry point called haigha that calls haigha.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - haigha
    - haigha.classes
    - haigha.connections
    - haigha.frames
    - haigha.transports

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/agoragames/haigha
  license: BSD License
  summary: 'Synchronous and asynchronous AMQP client library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
