package:
  name: flask-pymongo
  version: "0.3.1"

source:
  fn: Flask-PyMongo-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/F/Flask-PyMongo/Flask-PyMongo-0.3.1.tar.gz
  md5: aea20f9745ea33cf67fc310f25ea5643
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-pymongo = flask-pymongo:main
    #
    # Would create an entry point called flask-pymongo that calls flask-pymongo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask >=0.8
    - pymongo >=2.4,<3.0

  run:
    - python
    - flask >=0.8
    - pymongo >=2.4,<3.0

test:
  # Python imports
  imports:
    - flask_pymongo
    - tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://flask-pymongo.readthedocs.org/
  license: BSD License
  summary: 'PyMongo support for Flask applications'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
