package:
  name: nma-python
  version: "0.2.4"

source:
  fn: nma-python-0.2.4.tar.gz
  url: https://pypi.python.org/packages/source/n/nma-python/nma-python-0.2.4.tar.gz
  md5: 6f24c3e764989d8ae435613c8f1cc290
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nma-python = nma-python:main
    #
    # Would create an entry point called nma-python that calls nma-python.main()

    - nma_cli = nma.nma:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - argparse
    - httplib2

  run:
    - python
    - argparse
    - httplib2

test:
  # Python imports
  imports:
    - nma

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - nma_cli --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/thekad/nma-python
  license: MIT License
  summary: 'A library/cli tool for notifymyandroid (http://nma.usk.bz)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
