package:
  name: peewee
  version: "2.6.1"

source:
  fn: peewee-2.6.1.tar.gz
  url: https://pypi.python.org/packages/source/p/peewee/peewee-2.6.1.tar.gz
  md5: c597c28d62da14e38be018a2e0723dee
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - peewee = peewee:main
    #
    # Would create an entry point called peewee that calls peewee.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - playhouse

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/coleifer/peewee/
  license: MIT License
  summary: 'a little orm'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
