package:
  name: slumber
  version: "0.7.1"

source:
  fn: slumber-0.7.1.tar.gz
  url: https://pypi.python.org/packages/source/s/slumber/slumber-0.7.1.tar.gz
  md5: 58fe531e23b7324b9fbd3faa89a115e2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - slumber = slumber:main
    #
    # Would create an entry point called slumber that calls slumber.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests

  run:
    - python
    - requests

test:
  # Python imports
  imports:
    - slumber

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - unittest2
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/samgiles/slumber
  license: UNKNOWN
  summary: 'A library that makes consuming a REST API easier and more convenient'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
