package:
  name: moar
  version: "1.3.3"

source:
  fn: Moar-1.3.3.tar.gz
  url: https://pypi.python.org/packages/source/M/Moar/Moar-1.3.3.tar.gz
  md5: 508eb7590e95ddf74c540ddf42282f57
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - moar = moar:main
    #
    # Would create an entry point called moar that calls moar.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - moar

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/lucuma/Moar
  license: MIT License
  summary: 'Easy thumbnails for everyone'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
