package:
  name: lesscpy
  version: "0.10.2"

source:
  fn: lesscpy-0.10.2.tar.gz
  url: https://pypi.python.org/packages/source/l/lesscpy/lesscpy-0.10.2.tar.gz
  md5: fedbad1f4eb19c3af37f09560156246d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - lesscpy = lesscpy:main
    #
    # Would create an entry point called lesscpy that calls lesscpy.main()

    - lesscpy = lesscpy.scripts.compiler:run

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - ply
    - six

  run:
    - python
    - ply
    - six

test:
  # Python imports
  imports:
    - lesscpy
    - lesscpy.lessc
    - lesscpy.lib
    - lesscpy.plib
    - lesscpy.scripts

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - lesscpy --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage
    - flake8
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/lesscpy/lesscpy
  license: MIT License
  summary: 'Python LESS compiler'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
