package:
  name: lepl
  version: "5.1.3"

source:
  fn: LEPL-5.1.3.tar.gz
  url: https://pypi.python.org/packages/source/L/LEPL/LEPL-5.1.3.tar.gz
  md5: 5f653984c57ad8efad828c5153660743
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - lepl = lepl:main
    #
    # Would create an entry point called lepl that calls lepl.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - lepl
    - lepl._example
    - lepl._test
    - lepl.apps
    - lepl.apps._test
    - lepl.bin
    - lepl.bin._example
    - lepl.bin._test
    - lepl.contrib
    - lepl.core
    - lepl.core._test
    - lepl.lexer
    - lepl.lexer._example
    - lepl.lexer._test
    - lepl.lexer.lines
    - lepl.lexer.lines._example
    - lepl.lexer.lines._test
    - lepl.matchers
    - lepl.matchers._test
    - lepl.regexp
    - lepl.regexp._test
    - lepl.stream
    - lepl.stream._test
    - lepl.support
    - lepl.support._test

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.acooke.org/lepl/
  license: GNU Library or Lesser General Public License (LGPL) or Mozilla Public License 1.1 (MPL 1.1)
  summary: 'A Parser Library for Python 2.6+/3+: Recursive Descent; Full Backtracking'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
