package:
  name: pylons
  version: "1.0.1"

source:
  fn: Pylons-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/P/Pylons/Pylons-1.0.1.tar.gz
  md5: 6cb880d75fa81213192142b07a6e4915
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pylons = pylons:main
    #
    # Would create an entry point called pylons that calls pylons.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - routes >=1.12.3
    - webhelpers >=0.6.4
    - beaker >=1.5.4
    - paste >=1.7.5.1
    - pastedeploy >=1.5.0
    - pastescript >=1.7.4.2
    - formencode >=1.2.4
    - simplejson >=2.2.1
    - decorator >=3.3.2
    - nose >=1.1.2
    - mako >=0.5.0
    - weberror >=0.10.3
    - webtest >=1.3.1
    - tempita >=0.5.1
    - markupsafe >=0.15
    - webob >=1.1.1
    - jinja2
    - genshi >=0.6

  run:
    - python
    - routes >=1.12.3
    - webhelpers >=0.6.4
    - beaker >=1.5.4
    - paste >=1.7.5.1
    - pastedeploy >=1.5.0
    - pastescript >=1.7.4.2
    - formencode >=1.2.4
    - simplejson >=2.2.1
    - decorator >=3.3.2
    - nose >=1.1.2
    - mako >=0.5.0
    - weberror >=0.10.3
    - webtest >=1.3.1
    - tempita >=0.5.1
    - markupsafe >=0.15
    - webob >=1.1.1
    - jinja2
    - genshi >=0.6

test:
  # Python imports
  imports:
    - pylons
    - pylons.controllers
    - pylons.decorators
    - pylons.i18n
    - pylons.templates
    - test_files
    - test_files.sample_controllers
    - test_files.sample_controllers.controllers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage >=2.85
    - genshi
    - jinja2 >=2.2.1
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pylonshq.com/
  license: BSD License
  summary: 'Pylons Web Framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
