package:
  name: sprox
  version: "0.9.5"

source:
  fn: sprox-0.9.5.tar.gz
  url: https://pypi.python.org/packages/source/s/sprox/sprox-0.9.5.tar.gz
  md5: 12c85c3c815b3d64f0fe8d8a17b1b31e
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sprox = sprox:main
    #
    # Would create an entry point called sprox that calls sprox.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - formencode >=1.3.0a1
    - markupsafe
    - sqlalchemy
    - sieve
    - tw2.forms
    - genshi
    - mako
    - ming
    - sqlalchemy
    - sieve
    - tw2.forms
    - genshi
    - mako

  run:
    - python
    - formencode >=1.3.0a1
    - markupsafe
    - sqlalchemy
    - sieve
    - tw2.forms
    - genshi
    - mako
    - ming
    - sqlalchemy
    - sieve
    - tw2.forms
    - genshi
    - mako

test:
  # Python imports
  imports:
    - sprox
    - sprox.dojo
    - sprox.mg
    - sprox.mk
    - sprox.mootools
    - sprox.sa
    - sprox.widgets
    - sprox.widgets.tw1widgets
    - sprox.widgets.tw1widgets.templates
    - sprox.widgets.tw1widgets.test
    - sprox.widgets.tw2widgets
    - sprox.widgets.tw2widgets.templates

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - sieve
    - sqlalchemy
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.sprox.org
  license: MIT License
  summary: 'A package for creation of web widgets directly from database schema.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
