package:
  name: zope.tales
  version: "4.1.1"

source:
  fn: zope.tales-4.1.1.tar.gz
  url: https://pypi.python.org/packages/source/z/zope.tales/zope.tales-4.1.1.tar.gz
  md5: 28d03c7e7578340397a4a36623839482
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zope.tales = zope.tales:main
    #
    # Would create an entry point called zope.tales that calls zope.tales.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - zope.interface
    - six
    - zope.tal
    - zope.testing

  run:
    - python
    - setuptools
    - zope.interface
    - six
    - zope.tal
    - zope.testing

test:
  # Python imports
  imports:
    - zope
    - zope.tales
    - zope.tales.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - zope.testing
    - zope.testrunner
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/zope.tales
  license: Zope Public License
  summary: 'Zope Template Application Language Expression Syntax (TALES)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
