package:
  name: wsgiutils
  version: "0.7"

source:
  fn: WSGIUtils-0.7.tar.gz
  url: https://pypi.python.org/packages/source/W/WSGIUtils/WSGIUtils-0.7.tar.gz
  md5: 5c3a50a19f953bba136f964f5cd1185a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wsgiutils = wsgiutils:main
    #
    # Would create an entry point called wsgiutils that calls wsgiutils.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - wsgiutils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.owlfish.com/software/wsgiutils/index.html
  license: UNKNOWN
  summary: 'WSGI Utils are a collection of useful libraries for use in a WSGI environnment.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
