package:
  name: pretend
  version: "1.0.8"

source:
  fn: pretend-1.0.8.tar.gz
  url: https://pypi.python.org/packages/source/p/pretend/pretend-1.0.8.tar.gz
  md5: 7147050a95c9f494248557b42b58ad79
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pretend = pretend:main
    #
    # Would create an entry point called pretend that calls pretend.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/alex/pretend
  license: BSD License
  summary: 'A library for stubbing in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
