package:
  name: recaptcha-client
  version: "1.0.6"

source:
  fn: recaptcha-client-1.0.6.tar.gz
  url: https://pypi.python.org/packages/source/r/recaptcha-client/recaptcha-client-1.0.6.tar.gz
  md5: 74228180f7e1fb76c4d7089160b0d919
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - recaptcha-client = recaptcha-client:main
    #
    # Would create an entry point called recaptcha-client that calls recaptcha-client.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pycrypto

  run:
    - python
    - pycrypto

test:
  # Python imports
  imports:
    - recaptcha
    - recaptcha.client

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://recaptcha.net
  license: MIT/X11
  summary: 'A plugin for reCAPTCHA and reCAPTCHA Mailhide'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
