package:
  name: django-guardian
  version: "1.3"

source:
  fn: django-guardian-1.3.tar.gz
  url: https://pypi.python.org/packages/source/d/django-guardian/django-guardian-1.3.tar.gz
  md5: 5e90f213bf43f0eab1cc674bc06974e9
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-guardian = django-guardian:main
    #
    # Would create an entry point called django-guardian that calls django-guardian.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - django
    - six

  run:
    - python
    - django
    - six

test:
  # Python imports
  imports:
    - guardian
    - guardian.conf
    - guardian.management
    - guardian.management.commands
    - guardian.migrations
    - guardian.south_migrations
    - guardian.templatetags
    - guardian.testapp
    - guardian.testapp.migrations
    - guardian.testapp.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/lukaszb/django-guardian
  license: BSD License
  summary: 'Implementation of per object permissions for Django 1.2 or later.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
