package:
  name: pythonbrew
  version: "1.3.6"

source:
  fn: pythonbrew-1.3.6.tar.gz
  url: https://pypi.python.org/packages/source/p/pythonbrew/pythonbrew-1.3.6.tar.gz
  md5: aa968680a8b61fdc034ce01b31311614
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pythonbrew = pythonbrew:main
    #
    # Would create an entry point called pythonbrew that calls pythonbrew.main()

    - pythonbrew_install=pythonbrew.installer:install_pythonbrew
    - pythonbrew_systemwide=pythonbrew.installer:systemwide_pythonbrew

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pythonbrew
    - pythonbrew.commands
    - pythonbrew.installer
    - tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pythonbrew_install --help
    - pythonbrew_systemwide --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/utahta/pythonbrew
  license: MIT License
  summary: 'Manage python installations in your $HOME'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
