package:
  name: xlwt
  version: "1.0.0"

source:
  fn: xlwt-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/x/xlwt/xlwt-1.0.0.tar.gz
  md5: 5e5e4eae8fe7ee3d43f9324767ad925e
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - xlwt = xlwt:main
    #
    # Would create an entry point called xlwt that calls xlwt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - xlwt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.python-excel.org/
  license: BSD License
  summary: 'Library to create spreadsheet files compatible with MS Excel 97/2000/XP/2003 XLS files, on any platform, with Python 2.6, 2.6, 3.3+'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
