package:
  name: robotframework-ride
  version: "1.4"

source:
  fn: robotframework-ride-1.4.tar.gz
  url: https://pypi.python.org/packages/source/r/robotframework-ride/robotframework-ride-1.4.tar.gz
  md5: ea8d3e36b7ec1940e89b683eb14ffbdc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - robotframework-ride = robotframework-ride:main
    #
    # Would create an entry point called robotframework-ride that calls robotframework-ride.main()

    - pygmentize = pygments.cmdline:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pygments
    - pygments.filters
    - pygments.formatters
    - pygments.lexers
    - pygments.styles

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pygmentize --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pygments.org/
  license: BSD License
  summary: 'Pygments is a syntax highlighting package written in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
