package:
  name: moznetwork
  version: "0.26"

source:
  fn: moznetwork-0.26.tar.gz
  url: https://pypi.python.org/packages/source/m/moznetwork/moznetwork-0.26.tar.gz
  md5: 0badd9ca1575f2d8918a5f38b61a57dc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - moznetwork = moznetwork:main
    #
    # Would create an entry point called moznetwork that calls moznetwork.main()

    - moznetwork = moznetwork:cli

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - mozinfo
    - mozlog >=2.11

  run:
    - python
    - mozinfo
    - mozlog >=2.11

test:
  # Python imports
  imports:
    - moznetwork

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - moznetwork --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://wiki.mozilla.org/Auto-tools/Projects/Mozbase
  license: MPL
  summary: 'Library of network utilities for use in Mozilla testing'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
