package:
  name: z3c.recipe.scripts
  version: "1.0.1"

source:
  fn: z3c.recipe.scripts-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/z/z3c.recipe.scripts/z3c.recipe.scripts-1.0.1.tar.gz
  md5: 06f14b844047e053e709b7b8d03d131f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - z3c.recipe.scripts = z3c.recipe.scripts:main
    #
    # Would create an entry point called z3c.recipe.scripts that calls z3c.recipe.scripts.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - zc.buildout >=1.5.0
    - zc.recipe.egg >=1.3.0
    - setuptools

  run:
    - python
    - setuptools
    - zc.buildout >=1.5.0
    - zc.recipe.egg >=1.3.0
    - setuptools

test:
  # Python imports
  imports:
    - z3c
    - z3c.recipe
    - z3c.recipe.scripts

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - zope.testing
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://cheeseshop.python.org/pypi/z3c.recipe.scripts
  license: Zope Public License
  summary: 'Recipe for installing Python scripts'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
