package:
  name: django-hvad
  version: "1.2.2"

source:
  fn: django-hvad-1.2.2.tar.gz
  url: https://pypi.python.org/packages/source/d/django-hvad/django-hvad-1.2.2.tar.gz
  md5: bf82001d4b21d7bd74271d0d83186cd2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-hvad = django-hvad:main
    #
    # Would create an entry point called django-hvad that calls django-hvad.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - django >=1.4

  run:
    - python
    - django >=1.4

test:
  # Python imports
  imports:
    - hvad
    - hvad.contrib
    - hvad.contrib.restframework
    - hvad.test_utils
    - hvad.test_utils.project
    - hvad.test_utils.project.alternate_models_app
    - hvad.test_utils.project.alternate_models_app.models
    - hvad.test_utils.project.app

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/KristianOellegaard/django-hvad
  license: BSD License
  summary: 'A content translation framework for django integrated automatically in the normal ORM. Removes the pain of having to think about translations in a django project.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
