package:
  name: django-rosetta
  version: "0.7.6"

source:
  fn: django-rosetta-0.7.6.tar.gz
  url: https://pypi.python.org/packages/source/d/django-rosetta/django-rosetta-0.7.6.tar.gz
  md5: b41632f1b611c632bd937d60d9f966be
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-rosetta = django-rosetta:main
    #
    # Would create an entry point called django-rosetta that calls django-rosetta.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.2.0
    - django >=1.3
    - requests >=2.1.0
    - polib >=1.0.6
    - microsofttranslator ==0.5

  run:
    - python
    - six >=1.2.0
    - django >=1.3
    - requests >=2.1.0
    - polib >=1.0.6
    - microsofttranslator ==0.5

test:
  # Python imports
  imports:
    - rosetta
    - rosetta.conf
    - rosetta.templatetags
    - rosetta.tests
    - rosetta.tests.test_app

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mbi/django-rosetta
  license: MIT License
  summary: 'A Django application that eases the translation of Django projects'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
