package:
  name: peppercorn
  version: "0.5"

source:
  fn: peppercorn-0.5.tar.gz
  url: https://pypi.python.org/packages/source/p/peppercorn/peppercorn-0.5.tar.gz
  md5: f08efbca5790019ab45d76b7244abd40
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - peppercorn = peppercorn:main
    #
    # Would create an entry point called peppercorn that calls peppercorn.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - peppercorn

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://docs.pylonsproject.org/projects/peppercorn/en/latest/
  license: BSD-derived (http://www.repoze.org/LICENSE.txt)
  summary: 'A library for converting a token stream into a data structure for use in web form posts'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
