package:
  name: persistent
  version: "4.1.1"

source:
  fn: persistent-4.1.1.tar.gz
  url: https://pypi.python.org/packages/source/p/persistent/persistent-4.1.1.tar.gz
  md5: 57a9f99383afd946f1c1cd071a60adfb
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - persistent = persistent:main
    #
    # Would create an entry point called persistent that calls persistent.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - zope.interface
    - sphinx
    - repoze.sphinx.autointerface
    - nose
    - coverage

  run:
    - python
    - zope.interface
    - sphinx
    - repoze.sphinx.autointerface
    - nose
    - coverage

test:
  # Python imports
  imports:
    - persistent
    - persistent.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.zope.org/Products/ZODB
  license: Zope Public License
  summary: 'Translucent persistent objects'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
