package:
  name: dotcloud
  version: "0.9.8"

source:
  fn: dotcloud-0.9.8.tar.gz
  url: https://pypi.python.org/packages/source/d/dotcloud/dotcloud-0.9.8.tar.gz
  md5: 3677d6915a99f2bceaae42a2308bf981
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dotcloud = dotcloud:main
    #
    # Would create an entry point called dotcloud that calls dotcloud.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - argparse
    - requests >=1.1.0,<1.3.0
    - colorama

  run:
    - python
    - argparse
    - requests >=1.1.0,<1.3.0
    - colorama

test:
  # Python imports
  imports:
    - dotcloud
    - dotcloud.client
    - dotcloud.packages
    - dotcloud.ui

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.dotcloud.com/
  license: UNKNOWN
  summary: 'dotCloud command-line interface client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
