package:
  name: grappelli_safe
  version: "0.3.13"

source:
  fn: grappelli_safe-0.3.13.tar.gz
  url: https://pypi.python.org/packages/source/g/grappelli_safe/grappelli_safe-0.3.13.tar.gz
  md5: 5c8c681a0b1df94ecd6dc0b3a8b80892
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - grappelli_safe = grappelli_safe:main
    #
    # Would create an entry point called grappelli_safe that calls grappelli_safe.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - grappelli_safe

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/stephenmcd/grappelli-safe/
  license: UNKNOWN
  summary: 'A snapshot of the grappelli_2 branch of django-grappelli, packaged as a dependency for the Mezzanine CMS for Django.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
