package:
  name: python-designateclient
  version: "1.3.0"

source:
  fn: python-designateclient-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-designateclient/python-designateclient-1.3.0.tar.gz
  md5: f621e61e397fba7a26c0ac1fd96629c0
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-designateclient = python-designateclient:main
    #
    # Would create an entry point called python-designateclient that calls python-designateclient.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'OpenStack DNS as a Service - Client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
