package:
  name: pycups
  version: "1.9.72"

source:
  fn: pycups-1.9.72.tar.bz2
  url: https://pypi.python.org/packages/source/p/pycups/pycups-1.9.72.tar.bz2
  md5: c790bfbf4a3e9da2412c12c860fe191f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycups = pycups:main
    #
    # Would create an entry point called pycups that calls pycups.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://cyberelk.net/tim/software/pycups/
  license: GNU General Public License (GPL)
  summary: 'Python bindings for libcups'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
