package:
  name: pyrabbit
  version: "1.1.0"

source:
  fn: pyrabbit-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyrabbit/pyrabbit-1.1.0.tar.gz
  md5: 625013ba47fe79d296b76a74200c3312
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyrabbit = pyrabbit:main
    #
    # Would create an entry point called pyrabbit that calls pyrabbit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - httplib2

  run:
    - python
    - httplib2

test:
  # Python imports
  imports:
    - pyrabbit

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.github.com/bkjones/pyrabbit
  license: MIT License
  summary: 'A Pythonic interface to the RabbitMQ Management HTTP API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
