package:
  name: rackspace-auth-openstack
  version: "1.3"

source:
  fn: rackspace-auth-openstack-1.3.tar.gz
  url: https://pypi.python.org/packages/source/r/rackspace-auth-openstack/rackspace-auth-openstack-1.3.tar.gz
  md5: a75443cb14e3218650bb9dffb46ef8be
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rackspace-auth-openstack = rackspace-auth-openstack:main
    #
    # Would create an entry point called rackspace-auth-openstack that calls rackspace-auth-openstack.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-novaclient

  run:
    - python
    - setuptools
    - python-novaclient

test:
  # Python imports
  imports:
    - rackspace_auth_openstack

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/rackerlabs/rackspace-auth-openstack
  license: Apache Software License
  summary: 'Rackspace Auth Plugin for OpenStack Clients.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
