package:
  name: validictory
  version: "1.0.0"

source:
  fn: validictory-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/v/validictory/validictory-1.0.0.tar.gz
  md5: 0e2eb442d2d489c08b2c3a607b3c707a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - validictory = validictory:main
    #
    # Would create an entry point called validictory that calls validictory.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - validictory
    - validictory.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/sunlightlabs/validictory
  license: BSD License
  summary: 'general purpose python data validator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
