package:
  name: webcolors
  version: "1.5"

source:
  fn: webcolors-1.5.tar.gz
  url: https://pypi.python.org/packages/source/w/webcolors/webcolors-1.5.tar.gz
  md5: 2e9da1bbb7a087c6108e05be64640afb
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - webcolors = webcolors:main
    #
    # Would create an entry point called webcolors that calls webcolors.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ubernostrum/webcolors
  license: BSD License
  summary: 'A library for working with color names and color value formats defined by the HTML and CSS specifications for use in documents on the Web.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
