package:
  name: socketpool
  version: "0.5.3"

source:
  fn: socketpool-0.5.3.tar.gz
  url: https://pypi.python.org/packages/source/s/socketpool/socketpool-0.5.3.tar.gz
  md5: 24f542abc27293bf40c5223f2f8fb966
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - socketpool = socketpool:main
    #
    # Would create an entry point called socketpool that calls socketpool.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - socketpool

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/benoitc/socketpool
  license: MIT License
  summary: 'Python socket pool'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
