package:
  name: webhelpers
  version: "1.3"

source:
  fn: WebHelpers-1.3.tar.gz
  url: https://pypi.python.org/packages/source/W/WebHelpers/WebHelpers-1.3.tar.gz
  md5: 32749ffadfc40fea51075a7def32588b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - webhelpers = webhelpers:main
    #
    # Would create an entry point called webhelpers that calls webhelpers.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - markupsafe >=0.9.2

  run:
    - python
    - markupsafe >=0.9.2

test:
  # Python imports
  imports:
    - webhelpers
    - webhelpers.html
    - webhelpers.pylonslib

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    - routes
    - webob
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://webhelpers.groovie.org/
  license: BSD License
  summary: 'Web Helpers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
