package:
  name: rpyc
  version: "3.3.0"

source:
  fn: rpyc-3.3.0.tar.gz
  url: https://pypi.python.org/packages/source/r/rpyc/rpyc-3.3.0.tar.gz
  md5: 6931cb92c41f547591b525142ccaeef1
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rpyc = rpyc:main
    #
    # Would create an entry point called rpyc that calls rpyc.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - plumbum

  run:
    - python
    - plumbum

test:
  # Python imports
  imports:
    - rpyc
    - rpyc.core
    - rpyc.experimental
    - rpyc.lib
    - rpyc.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://rpyc.readthedocs.org
  license: MIT License
  summary: 'Remote Python Call (RPyC), a transparent and symmetric RPC library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
