package:
  name: strangecase
  version: "4.6.5"

source:
  fn: StrangeCase-4.6.5.tar.gz
  url: https://pypi.python.org/packages/source/S/StrangeCase/StrangeCase-4.6.5.tar.gz
  md5: 834d62257d3960bc63f17063f85f77e2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - strangecase = strangecase:main
    #
    # Would create an entry point called strangecase that calls strangecase.main()

    - scase = strange_case.__main__:run

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - jinja2
    - pyyaml
    - watchdog
    - plywood

  run:
    - python
    - jinja2
    - pyyaml
    - watchdog
    - plywood

test:
  # Python imports
  imports:
    - strange_case
    - strange_case.configurators
    - strange_case.extensions
    - strange_case.nodes
    - strange_case.support

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - scase --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/colinta/StrangeCase
  license: BSD License
  summary: 'A straightforward python static site generator.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
