package:
  name: aiohttp
  version: "0.16.5"

source:
  fn: aiohttp-0.16.5.tar.gz
  url: https://pypi.python.org/packages/source/a/aiohttp/aiohttp-0.16.5.tar.gz
  md5: 5ad92f63f423c53c139c2cecb25242f2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - aiohttp = aiohttp:main
    #
    # Would create an entry point called aiohttp that calls aiohttp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - chardet
    - asyncio

  run:
    - python
    - chardet
    - asyncio

test:
  # Python imports
  imports:
    - aiohttp

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - asyncio
    - chardet
    - gunicorn
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/KeepSafe/aiohttp/
  license: Apache Software License
  summary: 'http client/server for asyncio'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
