package:
  name: simples3
  version: "1.0"

source:
  fn: simples3-1.0.tar.gz
  url: https://pypi.python.org/packages/source/s/simples3/simples3-1.0.tar.gz
  md5: fc8d4c4dae6b068e42f5b2c5d05b0134
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - simples3 = simples3:main
    #
    # Would create an entry point called simples3 that calls simples3.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - simples3

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://sendapatch.se/projects/simples3/
  license: UNKNOWN
  summary: 'Simple, quick Amazon AWS S3 interface'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
