package:
  name: pam
  version: "0.1.4"

source:
  fn: pam-0.1.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pam/pam-0.1.4.tar.gz
  md5: 4c5247af579352bb6882dac64be10a33
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pam = pam:main
    #
    # Would create an entry point called pam that calls pam.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://atlee.ca/software/pam
  license: MIT License
  summary: 'PAM interface using ctypes'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
