package:
  name: django-nose
  version: "1.4.1"

source:
  fn: django-nose-1.4.1.tar.gz
  url: https://pypi.python.org/packages/source/d/django-nose/django-nose-1.4.1.tar.gz
  md5: 6ad999044299bc5e7fdc139f3c3c99b2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-nose = django-nose:main
    #
    # Would create an entry point called django-nose that calls django-nose.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - nose >=1.2.1
    - django >=1.4

  run:
    - python
    - nose >=1.2.1
    - django >=1.4

test:
  # Python imports
  imports:
    - django_nose
    - django_nose.management
    - django_nose.management.commands

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - south >=0.7
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/django-nose/django-nose
  license: BSD License
  summary: 'Makes your Django tests simple and snappy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
