package:
  name: functools32
  version: "3.2.3-1"

source:
  fn: functools32-3.2.3-1.tar.gz
  url: https://pypi.python.org/packages/source/f/functools32/functools32-3.2.3-1.tar.gz
  md5: 6c226dfc1ca56ba3ee200d603b780cbc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - functools32 = functools32:main
    #
    # Would create an entry point called functools32 that calls functools32.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - functools32

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/MiCHiLU/python-functools32
  license: PSF license
  summary: 'Backport of the functools module from Python 3.2.3 for use on 2.7 and PyPy.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
