package:
  name: twitter
  version: "1.17.0"

source:
  fn: twitter-1.17.0.tar.gz
  url: https://pypi.python.org/packages/source/t/twitter/twitter-1.17.0.tar.gz
  md5: f5e412264759dd6ebde16c6554b8cf34
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - twitter = twitter:main
    #
    # Would create an entry point called twitter that calls twitter.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - twitter

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mike.verdone.ca/twitter/
  license: MIT License
  summary: 'An API and command-line toolset for Twitter (twitter.com)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
