package:
  name: blockdiag
  version: "1.5.2"

source:
  fn: blockdiag-1.5.2.tar.gz
  url: https://pypi.python.org/packages/source/b/blockdiag/blockdiag-1.5.2.tar.gz
  md5: 6c1ffbb1cef161436cf2d80142616bc8
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - blockdiag = blockdiag:main
    #
    # Would create an entry point called blockdiag that calls blockdiag.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - funcparserlib
    - pillow
    - webcolors
    - docutils
    - reportlab
    - nose
    - mock
    - pep8 >=1.3
    - reportlab
    - docutils

  run:
    - python
    - setuptools
    - funcparserlib
    - pillow
    - webcolors
    - docutils
    - reportlab
    - nose
    - mock
    - pep8 >=1.3
    - reportlab
    - docutils

test:
  # Python imports
  imports:
    - blockdiag
    - blockdiag.imagedraw
    - blockdiag.imagedraw.filters
    - blockdiag.imagedraw.utils
    - blockdiag.noderenderer
    - blockdiag.noderenderer.flowchart
    - blockdiag.plugins
    - blockdiag.tests
    - blockdiag.tests.rst
    - blockdiag.utils
    - blockdiag.utils.rst

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - docutils
    - mock
    - nose
    - pep8 >=1.3
    - reportlab
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://blockdiag.com/
  license: Apache Software License
  summary: 'blockdiag generates block-diagram image from text'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
