package:
  name: pastescript
  version: "2.0.2"

source:
  fn: PasteScript-2.0.2.tar.gz
  url: https://pypi.python.org/packages/source/P/PasteScript/PasteScript-2.0.2.tar.gz
  md5: ccb3045445097192ca71a13b746c77b2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pastescript = pastescript:main
    #
    # Would create an entry point called pastescript that calls pastescript.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - paste >=1.3
    - pastedeploy
    - six
    - cheetah
    - flup
    - wsgiutils
    - pastedeploy
    - cheetah
    - pastedeploy

  run:
    - python
    - paste >=1.3
    - pastedeploy
    - six
    - cheetah
    - flup
    - wsgiutils
    - pastedeploy
    - cheetah
    - pastedeploy

test:
  # Python imports
  imports:
    - paste
    - paste.script
    - paste.script.util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose >=0.11
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pythonpaste.org/script/
  license: MIT License
  summary: 'A pluggable command-line frontend, including commands to setup package file layouts'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
