package:
  name: oslo.db
  version: "2.0.0"

source:
  fn: oslo.db-2.0.0.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.db/oslo.db-2.0.0.tar.gz
  md5: 8a9a4289693371bab07cec1b00c92756
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oslo.db = oslo.db:main
    #
    # Would create an entry point called oslo.db that calls oslo.db.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'Oslo Database library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
