package:
  name: mandrill
  version: "1.0.57"

source:
  fn: mandrill-1.0.57.tar.gz
  url: https://pypi.python.org/packages/source/m/mandrill/mandrill-1.0.57.tar.gz
  md5: bcbd7ca3e69be4b16759bbc505c41ebf
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mandrill = mandrill:main
    #
    # Would create an entry point called mandrill that calls mandrill.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=0.13.2
    - docopt ==0.4.0

  run:
    - python
    - requests >=0.13.2
    - docopt ==0.4.0

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/mailchimp/mandrill-api-python/
  license: Apache Software License
  summary: 'A CLI client and Python API library for the Mandrill email as a service platform.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
