package:
  name: interlude
  version: "1.3.1"

source:
  fn: interlude-1.3.1.tar.gz
  url: https://pypi.python.org/packages/source/i/interlude/interlude-1.3.1.tar.gz
  md5: d05bb215a82fdadcc54e9c43a34fbc1c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - interlude = interlude:main
    #
    # Would create an entry point called interlude that calls interlude.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - ipython >=1.1.0

  run:
    - python
    - setuptools
    - ipython >=1.1.0

test:
  # Python imports
  imports:
    - interlude

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/collective/interlude
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Interlude for Doctests provides an Interactive Console.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
