package:
  name: psycogreen
  version: "1.0"

source:
  fn: psycogreen-1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/psycogreen/psycogreen-1.0.tar.gz
  md5: 7a32d8f5abdb4ce17ac512f8c8a698a9
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - psycogreen = psycogreen:main
    #
    # Would create an entry point called psycogreen that calls psycogreen.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - psycogreen

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/dvarrazzo/psycogreen
  license: BSD License
  summary: 'psycopg2 integration with coroutine libraries'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
