package:
  name: 4suite-xml
  version: "1.0.2"

source:
  fn: 4Suite-XML-1.0.2.tar.bz2
  url: https://pypi.python.org/packages/source/4/4Suite-XML/4Suite-XML-1.0.2.tar.bz2
  md5: b3e976a666899113d58f333518205968
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - 4suite-xml = 4suite-xml:main
    #
    # Would create an entry point called 4suite-xml that calls 4suite-xml.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://4suite.org/
  license: Apache Software License
  summary: 'An open-source platform for XML processing'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
