package:
  name: httpagentparser
  version: "1.7.7"

source:
  fn: httpagentparser-1.7.7.tar.gz
  url: https://pypi.python.org/packages/source/h/httpagentparser/httpagentparser-1.7.7.tar.gz
  md5: 1977d91ece2617e92fd5f1a5336e8320
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - httpagentparser = httpagentparser:main
    #
    # Would create an entry point called httpagentparser that calls httpagentparser.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - httpagentparser

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://shon.github.com/httpagentparser
  license: http://www.opensource.org/licenses/mit-license.php
  summary: 'Extracts OS Browser etc information from http user agent string'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
