package:
  name: s3config
  version: "0.1.2"

source:
  fn: v0.1.tar.gz
  url: https://bitbucket.org/jibbolo/s3config/get/v0.1.tar.gz
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - s3config = s3config:main
    #
    # Would create an entry point called s3config that calls s3config.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pyyaml >=3.11
    - boto >=2.28.0
    - wsgiref >=0.1.2

  run:
    - python
    - pyyaml >=3.11
    - boto >=2.28.0
    - wsgiref >=0.1.2

test:
  # Python imports
  imports:
    - s3config

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/jibbolo/s3config
  license: UNKNOWN
  summary: 'Read config file from Amazon S3 url'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
