package:
  name: urlfetch
  version: "1.0.2"

source:
  fn: urlfetch-1.0.2.tar.bz2
  url: https://pypi.python.org/packages/source/u/urlfetch/urlfetch-1.0.2.tar.bz2
  md5: 472e0bc760f7209bffdaeb71f3b330b5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - urlfetch = urlfetch:main
    #
    # Would create an entry point called urlfetch that calls urlfetch.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ifduyue/urlfetch
  license: BSD License
  summary: 'An easy to use HTTP client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
