package:
  name: wstool
  version: "0.1.6"

source:
  fn: wstool-0.1.6.tar.gz
  url: https://pypi.python.org/packages/source/w/wstool/wstool-0.1.6.tar.gz
  md5: 38cbe5a549c2c1eec017f6d92181674c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wstool = wstool:main
    #
    # Would create an entry point called wstool that calls wstool.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - vcstools >=0.1.34
    - pyyaml

  run:
    - python
    - vcstools >=0.1.34
    - pyyaml

test:
  # Python imports
  imports:
    - wstool

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://wiki.ros.org/wstool
  license: BSD License
  summary: 'workspace multi-SCM commands'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
