package:
  name: qds_sdk
  version: "1.6.1"

source:
  fn: qds_sdk-1.6.1.tar.gz
  url: https://pypi.python.org/packages/source/q/qds_sdk/qds_sdk-1.6.1.tar.gz
  md5: 25302c3e269d2621206f0c99fe1c1d14
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - qds_sdk = qds_sdk:main
    #
    # Would create an entry point called qds_sdk that calls qds_sdk.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=1.0.3
    - boto >=2.1.1
    - six >=1.2.0
    - urllib3 >=1.0.2

  run:
    - python
    - requests >=1.0.3
    - boto >=2.1.1
    - six >=1.2.0
    - urllib3 >=1.0.2

test:
  # Python imports
  imports:
    - qds_sdk

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/qubole/qds-sdk-py
  license: Apache Software License
  summary: 'Python SDK for coding to the Qubole Data Service API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
