package:
  name: neptuno2
  version: "1.2.3"

source:
  fn: Neptuno2-1.2.3.tar.gz
  url: https://pypi.python.org/packages/source/N/Neptuno2/Neptuno2-1.2.3.tar.gz
  md5: 9b69527f937272652f1632bee9afbf6b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - neptuno2 = neptuno2:main
    #
    # Would create an entry point called neptuno2 that calls neptuno2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - psycopg2
    - sqlalchemy
    - lxml
    - xlrd
    - xlwt
    - simplejson
    - jinja2

  run:
    - python
    - psycopg2
    - sqlalchemy
    - lxml
    - xlrd
    - xlwt
    - simplejson
    - jinja2

test:
  # Python imports
  imports:
    - neptuno
    - neptuno.postgres
    - neptuno.templates

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.ender.es
  license: UNKNOWN
  summary: 'A little set of utilities that Ender has been using in their web projects'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
