package:
  name: persistence
  version: "3.0a1"

source:
  fn: Persistence-3.0a1.zip
  url: https://pypi.python.org/packages/source/P/Persistence/Persistence-3.0a1.zip
  md5: 0551e04fbf180ff750880e5da31b4a6c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - persistence = persistence:main
    #
    # Would create an entry point called persistence that calls persistence.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - extensionclass >=4.1a1
    - persistent

  run:
    - python
    - extensionclass >=4.1a1
    - persistent

test:
  # Python imports
  imports:
    - Persistence
    - Persistence.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/Persistence
  license: Zope Public License
  summary: 'Persistent ExtensionClass'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
