package:
  name: cerberus
  version: "0.9"

source:
  fn: Cerberus-0.9.tar.gz
  url: https://pypi.python.org/packages/source/C/Cerberus/Cerberus-0.9.tar.gz
  md5: f2658eba752c3154f4b2297f229769bb
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cerberus = cerberus:main
    #
    # Would create an entry point called cerberus that calls cerberus.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - cerberus
    - cerberus.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/nicolaiarocci/cerberus
  license: ISC License (ISCL)
  summary: 'Extensible validation for Python dictionaries.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
