package:
  name: freezegun
  version: "0.3.4"

source:
  fn: freezegun-0.3.4.tar.gz
  url: https://pypi.python.org/packages/source/f/freezegun/freezegun-0.3.4.tar.gz
  md5: a88808a8c48e4e89b77fc9cc7105c418
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - freezegun = freezegun:main
    #
    # Would create an entry point called freezegun that calls freezegun.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six
    - python-dateutil >=1.0,!=2.0

  run:
    - python
    - six
    - python-dateutil >=1.0,!=2.0

test:
  # Python imports
  imports:
    - freezegun

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/spulec/freezegun
  license: UNKNOWN
  summary: 'Let your Python tests travel through time'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
