package:
  name: rax_scheduled_images_python_novaclient_ext
  version: "0.3.1"

source:
  fn: rax_scheduled_images_python_novaclient_ext-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/r/rax_scheduled_images_python_novaclient_ext/rax_scheduled_images_python_novaclient_ext-0.3.1.tar.gz
  md5: 14c28fc2a3627b1a2cef6cee537d7e84
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rax_scheduled_images_python_novaclient_ext = rax_scheduled_images_python_novaclient_ext:main
    #
    # Would create an entry point called rax_scheduled_images_python_novaclient_ext that calls rax_scheduled_images_python_novaclient_ext.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-novaclient

  run:
    - python
    - python-novaclient

test:
  # Python imports
  imports:
    - rax_scheduled_images_python_novaclient_ext

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/rackspace-titan/rax_scheduled_images_python_novaclient_ext
  license: Apache Software License
  summary: 'Extends python-novaclient to use RAX-SI, the Rackspace Nova API Scheduled Images extension'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
