package:
  name: djangorecipe
  version: "2.1.1"

source:
  fn: djangorecipe-2.1.1.tar.gz
  url: https://pypi.python.org/packages/source/d/djangorecipe/djangorecipe-2.1.1.tar.gz
  md5: 8d759591f3039038a6f4d7644236a6d7
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - djangorecipe = djangorecipe:main
    #
    # Would create an entry point called djangorecipe that calls djangorecipe.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - zc.buildout
    - zc.recipe.egg
    - django
    - coverage
    - mock

  run:
    - python
    - zc.buildout
    - zc.recipe.egg
    - django
    - coverage
    - mock

test:
  # Python imports
  imports:
    - djangorecipe
    - djangorecipe.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/rvanlaar/djangorecipe
  license: BSD License
  summary: 'Buildout recipe for Django'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
