package:
  name: catkin_pkg
  version: "0.2.9"

source:
  fn: catkin_pkg-0.2.9.tar.gz
  url: https://pypi.python.org/packages/source/c/catkin_pkg/catkin_pkg-0.2.9.tar.gz
  md5: 66b484e850748b38a5a66f70debc4914
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - catkin_pkg = catkin_pkg:main
    #
    # Would create an entry point called catkin_pkg that calls catkin_pkg.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - argparse
    - docutils
    - python-dateutil

  run:
    - python
    - argparse
    - docutils
    - python-dateutil

test:
  # Python imports
  imports:
    - catkin_pkg

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://wiki.ros.org/catkin_pkg
  license: BSD License
  summary: 'catkin package library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
