package:
  name: pygtail
  version: "0.5.3"

source:
  fn: pygtail-0.5.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pygtail/pygtail-0.5.3.tar.gz
  md5: bceb4bc60f13cddaecccc5fe39a64056
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pygtail = pygtail:main
    #
    # Would create an entry point called pygtail that calls pygtail.main()

    - pygtail=pygtail.core:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pygtail

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pygtail --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/bgreenlee/pygtail
  license: GNU General Public License (GPL)
  summary: 'Reads log file lines that have not been read.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
