package:
  name: nodeenv
  version: "0.13.2"

source:
  fn: nodeenv-0.13.2.tar.gz
  url: https://pypi.python.org/packages/source/n/nodeenv/nodeenv-0.13.2.tar.gz
  md5: 0528e970ec2c17b9ec243c0ed567dbb9
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nodeenv = nodeenv:main
    #
    # Would create an entry point called nodeenv that calls nodeenv.main()

    - nodeenv = nodeenv:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  # imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - nodeenv --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ekalinin/nodeenv
  license: BSD License
  summary: 'Node.js virtual environment builder'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
