package:
  name: xenapi
  version: "1.2"

source:
  fn: XenAPI-1.2.tar.gz
  url: https://pypi.python.org/packages/source/X/XenAPI/XenAPI-1.2.tar.gz
  md5: 655c59cf0f2d322f58e49bcba2baf129
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - xenapi = xenapi:main
    #
    # Would create an entry point called xenapi that calls xenapi.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://community.citrix.com/display/xs/Download+SDKs
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'XenAPI SDK, for communication with Citrix XenServer and Xen Cloud Platform.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
