package:
  name: pychef
  version: "0.2.3"

source:
  fn: PyChef-0.2.3.tar.gz
  url: https://pypi.python.org/packages/source/P/PyChef/PyChef-0.2.3.tar.gz
  md5: 56f4341d57fbff3fe396a4e52d198bc7
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pychef = pychef:main
    #
    # Would create an entry point called pychef that calls pychef.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - chef
    - chef.tests
    - chef.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - unittest2
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/coderanger/pychef
  license: BSD License
  summary: 'Python implementation of a Chef API client.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
