package:
  name: zope.tal
  version: "4.1.1"

source:
  fn: zope.tal-4.1.1.tar.gz
  url: https://pypi.python.org/packages/source/z/zope.tal/zope.tal-4.1.1.tar.gz
  md5: 29af9de79becc3bbb4588b3c65b4947e
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zope.tal = zope.tal:main
    #
    # Would create an entry point called zope.tal that calls zope.tal.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - zope.i18nmessageid
    - zope.interface
    - zope.testing

  run:
    - python
    - setuptools
    - zope.i18nmessageid
    - zope.interface
    - zope.testing

test:
  # Python imports
  imports:
    - zope
    - zope.tal
    - zope.tal.benchmark
    - zope.tal.tests
    - zope.tal.tests.input
    - zope.tal.tests.output

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - zope.testrunner
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/zope.tal
  license: Zope Public License
  summary: 'Zope Template Application Language (TAL)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
