package:
  name: rauth
  version: "0.7.1"

source:
  fn: rauth-0.7.1.tar.gz
  url: https://pypi.python.org/packages/source/r/rauth/rauth-0.7.1.tar.gz
  md5: 9c4518fc26f556be49b7f377db951a75
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rauth = rauth:main
    #
    # Would create an entry point called rauth that calls rauth.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=1.2.3

  run:
    - python
    - requests >=1.2.3

test:
  # Python imports
  imports:
    - rauth

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/litl/rauth
  license: MIT License
  summary: 'A Python library for OAuth 1.0/a, 2.0, and Ofly.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
