package:
  name: django-annoying
  version: "0.8.2"

source:
  fn: django-annoying-0.8.2.tar.gz
  url: https://pypi.python.org/packages/source/d/django-annoying/django-annoying-0.8.2.tar.gz
  md5: 95f8bdca8b1b6e2dce547af902319935
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-annoying = django-annoying:main
    #
    # Would create an entry point called django-annoying that calls django-annoying.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - annoying
    - annoying.templatetags
    - annoying.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/skorokithakis/django-annoying
  license: BSD
  summary: 'This is a django application that tries to eliminate annoying things in the Django framework.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
