package:
  name: python-termstyle
  version: "0.1.10"

source:
  fn: python-termstyle-0.1.10.tar.gz
  url: https://pypi.python.org/packages/source/p/python-termstyle/python-termstyle-0.1.10.tar.gz
  md5: 1b227cebbeda209029252420af72e5c7
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-termstyle = python-termstyle:main
    #
    # Would create an entry point called python-termstyle that calls python-termstyle.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://gfxmonk.net/dist/0install/python-termstyle.xml
  license: BSD License
  summary: 'console colouring for python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
