package:
  name: python-digest
  version: "1.7"

source:
  fn: python-digest-1.7.tar.gz
  url: https://pypi.python.org/packages/source/p/python-digest/python-digest-1.7.tar.gz
  md5: 472a33170f06e4c645d99e3a10c62894
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-digest = python-digest:main
    #
    # Would create an entry point called python-digest that calls python-digest.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - python_digest

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/akoha/python-digest/
  license: BSD License
  summary: 'A Python library to aid in implementing HTTP Digest Authentication.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
