package:
  name: cloud
  version: "2.8.5"

source:
  fn: cloud-2.8.5.tar.gz
  url: https://pypi.python.org/packages/source/c/cloud/cloud-2.8.5.tar.gz
  md5: 9b291fdd6a4f85065dae0f92e9ff7195
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cloud = cloud:main
    #
    # Would create an entry point called cloud that calls cloud.main()

    - picloud = cloud.cli.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - cloud
    - cloud.cli
    - cloud.serialization
    - cloud.shortcuts
    - cloud.transport
    - cloud.util
    - cloud.util.cloghandler

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - picloud --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.picloud.com
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'PiCloud client-side library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
