package:
  name: loremipsum
  version: "1.0.5"

source:
  fn: loremipsum-1.0.5.tar.gz
  url: https://pypi.python.org/packages/source/l/loremipsum/loremipsum-1.0.5.tar.gz
  md5: 813b2162d3dce4df0d1427360e462c49
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - loremipsum = loremipsum:main
    #
    # Would create an entry point called loremipsum that calls loremipsum.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - loremipsum

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://projects.monkeython.com/loremipsum
  license: GNU General Public License (GPL)
  summary: 'A Lorem Ipsum text generator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
