package:
  name: zope.testrunner
  version: "4.4.9"

source:
  fn: zope.testrunner-4.4.9.zip
  url: https://pypi.python.org/packages/source/z/zope.testrunner/zope.testrunner-4.4.9.zip
  md5: f8dd244ebe89f68c038c7054c2169d57
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zope.testrunner = zope.testrunner:main
    #
    # Would create an entry point called zope.testrunner that calls zope.testrunner.main()

    - zope-testrunner = zope.testrunner:run

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - setuptools
    - six
    - zope.exceptions
    - zope.interface
    - zope.testing
    - python-subunit

  run:
    - python
    - setuptools
    - setuptools
    - six
    - zope.exceptions
    - zope.interface
    - zope.testing
    - python-subunit

test:
  # Python imports
  imports:
    - zope
    - zope.testrunner
    - zope.testrunner.tests.testrunner-ex

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - zope-testrunner --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - python-subunit
    - zope.testing
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/zope.testrunner
  license: Zope Public License
  summary: 'Zope testrunner script.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
