package:
  name: django-redis-cache
  version: "1.1.0"

source:
  fn: django-redis-cache-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/d/django-redis-cache/django-redis-cache-1.1.0.tar.gz
  md5: 9ed5a3812ecdee2a5b4d946e6c136268
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-redis-cache = django-redis-cache:main
    #
    # Would create an entry point called django-redis-cache that calls django-redis-cache.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - redis >=2.4.5

  run:
    - python
    - redis >=2.4.5

test:
  # Python imports
  imports:
    - redis_cache
    - redis_cache.backends

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/sebleier/django-redis-cache/
  license: UNKNOWN
  summary: 'Redis Cache Backend for Django'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
