package:
  name: django-pagination
  version: "1.0.7"

source:
  fn: django-pagination-1.0.7.tar.gz
  url: https://pypi.python.org/packages/source/d/django-pagination/django-pagination-1.0.7.tar.gz
  md5: 43353a0b3344e5b10a9a83248a6dc24a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-pagination = django-pagination:main
    #
    # Would create an entry point called django-pagination that calls django-pagination.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pagination
    - pagination.templatetags

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://django-pagination.googlecode.com/
  license: BSD
  summary: 'django-pagination'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
