package:
  name: wsgi_intercept
  version: "0.10.0"

source:
  fn: wsgi_intercept-0.10.0.tar.gz
  url: https://pypi.python.org/packages/source/w/wsgi_intercept/wsgi_intercept-0.10.0.tar.gz
  md5: 5ef3b47dce89fd14e1d92fbc185f883b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wsgi_intercept = wsgi_intercept:main
    #
    # Would create an entry point called wsgi_intercept that calls wsgi_intercept.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytest >=2.4
    - httplib2
    - requests >=2.0.1

  run:
    - python
    - pytest >=2.4
    - httplib2
    - requests >=2.0.1

test:
  # Python imports
  imports:
    - test
    - wsgi_intercept

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/wsgi_intercept
  license: MIT License
  summary: 'wsgi_intercept installs a WSGI application in place of a real URI for testing.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
